"""Create users table

Revision ID: e88f496d26c3
Revises: 
Create Date: 2024-12-13 17:47:57.352259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e88f496d26c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('deadline',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('job_group')
        batch_op.drop_column('address_main')
        batch_op.drop_column('createdAt')
        batch_op.drop_column('crawledAt')
        batch_op.drop_column('url')
        batch_op.drop_column('experience')
        batch_op.drop_column('employment_type')
        batch_op.drop_column('salary')
        batch_op.drop_column('badge')
        batch_op.drop_column('tech_stack')
        batch_op.drop_column('address_total')
        batch_op.drop_column('education')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_total', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('tech_stack', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('badge', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('salary', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('employment_type', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('experience', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('url', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('crawledAt', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('createdAt', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('address_main', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('job_group', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('deadline',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('location')

    op.drop_table('users')
    op.drop_table('jobs')
    # ### end Alembic commands ###
